name: Deploy to EC2

on:
  push:
    branches:
      - ventas

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.PEM_FILE }}
      REMOTE_USER: ec2-user
      REMOTE_HOST: DireccionIPPublica
      APP_NAME: app.js

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "EC2 funcionando OK"
            sudo apt update -y
